export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const IS_AUTHENTICATED = "IS_AUTHENTICATED"
export const USER_REGISTARTION_SUCCESS = "USER_REGISTARTION_SUCCESS"

//Story Management
export const GET_ALL_STORIES = "GET_ALL_STORIES"
export const GET_ALL_STORIES_FULFILLED = "GET_ALL_STORIES_FULFILLED"
export const GET_MY_STORIES = "GET_MY_STORIES"
export const GET_MY_STORIES_FULFILLED = "GET_MY_STORIES_FULFILLED"
export const DELETE_STORY = "DELETE_STORY"
export const DELETE_STORY_REJECTED = "DELETE_STORY_REJECTED"
export const DELETE_STORY_FULFILLED = "DELETE_STORY_FULFILLED"