export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const IS_AUTHENTICATED = "IS_AUTHENTICATED"
export const USER_REGISTARTION_SUCCESS = "USER_REGISTARTION_SUCCESS"

//Story Management
export const GET_ALL_STORIES = "GET_ALL_STORIES"